### ISSUE TITLE
getting error on version 1.6.0

### ISSUE THREAD

**Issue by nijona** [DataDog/dd-native-iast-taint-tracking-js#76]
Using docker version: node:16.20.0-alpine3.16

getting this error on 1.6.0, (1.5.0 works fine)

`npm ERR! gyp: binding.gyp not found (cwd: /app/node_modules/@datadog/native-iast-taint-tracking) while trying to load binding.gyp`

any idea? @uurien 

Thanks!

**Comment by hoolioh** [comment]
Hi, were your trying to install from npm or building the package locally? Could you attach the whole log? If you're using a Dockerfile, could you attach it?

I had no luck trying to reproduce the problem in a fresh container, this is what I did: 
```
/tmp/app # cat /etc/alpine-release 
3.16.5
/tmp/app # npm init -y
Wrote to /tmp/app/package.json:

{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


/tmp/app # npm i @datadog/native-iast-taint-tracking

added 2 packages, and audited 3 packages in 3s

found 0 vulnerabilities
npm notice 
npm notice New major version of npm available! 8.19.4 -> 9.8.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.8.1
npm notice Run npm install -g npm@9.8.1 to update!
npm notice 
```

Also tried to build it in the same container and all went well:
```
apk add git make cmake g++ libexecinfo-dev python3
/tmp # git clone https://github.com/DataDog/dd-native-iast-taint-tracking-js.git
Cloning into 'dd-native-iast-taint-tracking-js'...
remote: Enumerating objects: 1210, done.
remote: Counting objects: 100% (860/860), done.
remote: Compressing objects: 100% (409/409), done.
remote: Total 1210 (delta 544), reused 666 (delta 451), pack-reused 350
Receiving objects: 100% (1210/1210), 494.51 KiB | 2.48 MiB/s, done.
Resolving deltas: 100% (694/694), done.
/tmp # cd dd-native-iast-taint-tracking-js/
/tmp/dd-native-iast-taint-tracking-js # npm i --ignore-scripts

added 307 packages, and audited 308 packages in 3s

78 packages are looking for funding
  run `npm fund` for details

4 vulnerabilities (2 moderate, 2 high)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
/tmp/dd-native-iast-taint-tracking-js # npm run build

> @datadog/native-iast-taint-tracking@1.6.0 build
> node-gyp configure && node-gyp build

gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@16.20.0 | linux | x64
gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/tmp/dd-native-iast-taint-tracking-js/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/dd-native-iast-taint-tracking-js/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/tmp/dd-native-iast-taint-tracking-js/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.cache/node-gyp/16.20.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/16.20.0',
gyp info spawn args   '-Dnode_gyp_dir=/tmp/dd-native-iast-taint-tracking-js/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/16.20.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/tmp/dd-native-iast-taint-tracking-js',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info ok 
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@16.20.0 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/tmp/dd-native-iast-taint-tracking-js/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
rm -f Release/obj.target/node_modules/node-addon-api/nothing.a Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/node_modules/node-addon-api/nothing.a`
ar crs Release/obj.target/node_modules/node-addon-api/nothing.a @Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list
  COPY Release/nothing.a
  CXX(target) Release/obj.target/iastnativemethods/src/gc/gc.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/utils/jsobject_utils.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/utils/propagation.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/tainted/input_info.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/tainted/range.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/tainted/tainted_object.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/tainted/transaction.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/tainted/string_resource.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/api/string_methods.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/api/concat.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/api/trim.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/api/slice.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/api/substring.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/api/replace.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/api/metrics.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
  CXX(target) Release/obj.target/iastnativemethods/src/iast.o
<command-line>: warning: ISO C++11 requires whitespace after the macro name
In file included from ../src/iast.cc:6:
/root/.cache/node-gyp/16.20.0/include/node/node.h:887:7: warning: cast between incompatible function types from 'void (*)(v8::Local<v8::Object>)' to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
  887 |       (node::addon_register_func) (regfunc),                          \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/16.20.0/include/node/node.h:921:3: note: in expansion of macro 'NODE_MODULE_X'
  921 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../src/iast.cc:58:1: note: in expansion of macro 'NODE_MODULE'
   58 | NODE_MODULE(NODE_GYP_MODULE_NAME, Init);
      | ^~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/iastnativemethods.node
  COPY Release/iastnativemethods.node
  COPY ../dist/iastnativemethods.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/tmp/dd-native-iast-taint-tracking-js/build'
gyp info ok 

> @datadog/native-iast-taint-tracking@1.6.0 postbuild
> node ./scripts/pack.js
```

**Comment by nadavyeru** [comment]
Hi @hoolioh 
Logs from the issue:

`06:25:02  npm ERR! code 1
06:25:02  npm ERR! path /app/node_modules/@datadog/native-iast-taint-tracking
06:25:02  npm ERR! command failed
06:25:02  npm ERR! command sh -c -- node-gyp rebuild
06:25:02  npm ERR! gyp info it worked if it ends with ok
06:25:02  npm ERR! gyp info using node-gyp@8.4.1
06:25:02  npm ERR! gyp info using node@16.20.0 | linux | x64
06:25:02  npm ERR! gyp ERR! find Python 
06:25:02  npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
06:25:02  npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
06:25:02  npm ERR! gyp ERR! find Python checking if "python3" can be used
06:25:02  npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
06:25:02  npm ERR! gyp ERR! find Python checking if "python" can be used
06:25:02  npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
06:25:02  npm ERR! gyp ERR! find Python 
06:25:02  npm ERR! gyp ERR! find Python **********************************************************
06:25:02  npm ERR! gyp ERR! find Python You need to install the latest version of Python.
06:25:02  npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
06:25:02  npm ERR! gyp ERR! find Python you can try one of the following options:
06:25:02  npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
06:25:02  npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
06:25:02  npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
06:25:02  npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
06:25:02  npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
06:25:02  npm ERR! gyp ERR! find Python For more information consult the documentation at:
06:25:02  npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
06:25:02  npm ERR! gyp ERR! find Python **********************************************************
06:25:02  npm ERR! gyp ERR! find Python 
06:25:02  npm ERR! gyp ERR! configure error 
06:25:02  npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
06:25:02  npm ERR! gyp ERR! stack     at PythonFinder.fail (/app/node_modules/node-gyp/lib/find-python.js:330:47)
06:25:02  npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/app/node_modules/node-gyp/lib/find-python.js:159:21)
06:25:02  npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/find-python.js:202:16)
06:25:02  npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/app/node_modules/node-gyp/lib/find-python.js:294:16)
06:25:02  npm ERR! gyp ERR! stack     at exithandler (node:child_process:410:5)
06:25:02  npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:422:5)
06:25:02  npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
06:25:02  npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
06:25:02  npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:485:16)
06:25:02  npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
06:25:02  npm ERR! gyp ERR! System Linux 5.4.0-1099-aws
06:25:02  npm ERR! gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-gyp" "rebuild"
06:25:02  npm ERR! gyp ERR! cwd /app/node_modules/@datadog/native-iast-taint-tracking
06:25:02  npm ERR! gyp ERR! node -v v16.20.0
06:25:02  npm ERR! gyp ERR! node-gyp -v v8.4.1
06:25:02  npm ERR! gyp ERR! not ok`

**Comment by hoolioh** [comment]
Hi @nadavyeru, 
Bear with me here, I'm trying to understand why the `node-gyp rebuild` is issued which is not supposed to happen because the package is shipped precompiled. What's the command you're executing before you see all the logs?

**Comment by miloconway** [comment]
I've ran into the same issue. Looking at https://registry.npmjs.org/@datadog%2fnative-iast-taint-tracking - I see that `"gypfile": true` is set for 1.6

**Comment by uurien** [comment]
`1.6.0` version has been deprecated in npm and `1.5.0` has been set as `latest`.  Hopefully it will fix your problems and we will analyze deeply what is happening.

**Comment by hoolioh** [comment]
It turned out that it was a combination of several factors. Firstly we changed the release process and that led to setting the property `gypfile` to `true` as @miloconway pointed out. Secondly that property only takes in effect when using a private proxy registry, like Verdaccio, that's why it went unnoticed during our tests.
As a result we've already taken measures to solve the issue and future releases won't have the `gypfile` property set.
If you all agree I will close the the issue. Thanks for the feedback.
